import { teamMem } from "../assets";

const navigationLinks = [
    { id: "01", name: "Home", route: "/" },
    { id: "02", name: "Report", route: "/report" },
    { id: "03", name: "Volunteer", route: "/volunteer" },
    { id: "04", name: "Donate", route: "/donate" },
    { id: "05", name: "About us", route: "/about" },
    { id: "06", name: "Sign In", route: "/signin" },
]

const teamMember = [
    { photoPath: teamMem, name: 'Ram Kumar thapa', post: 'Founding Member' },
    { photoPath: teamMem, name: 'Bimal Gharti Magar', post: 'Founding Member' },
    { photoPath: teamMem, name: 'Shankar Shah', post: 'Founding Member' }
]

const googleMapsApi = 'AIzaSyBLEaTTrzYWeyeL_0JVU2uPOxQTR08BCrg';

const messenger = {
    pageId: "106560697968888", appId: "561671326031331"
}
const childList =
    [{
        "id": 1,
        "name": "Jessi",
        "surname": "Leavold"
    }, {
        "id": 2,
        "name": "Yolanthe",
        "surname": "Tink"
    }, {
        "id": 3,
        "name": "Andria",
        "surname": "Spikins"
    }, {
        "id": 4,
        "name": "Viola",
        "surname": "Pickvance"
    }, {
        "id": 5,
        "name": "Robinetta",
        "surname": "Banbrick"
    }, {
        "id": 6,
        "name": "Rowen",
        "surname": "Totaro"
    }, {
        "id": 7,
        "name": "Gray",
        "surname": "Cranmor"
    }, {
        "id": 8,
        "name": "Linnell",
        "surname": "McReedy"
    }, {
        "id": 9,
        "name": "Franchot",
        "surname": "Waddilove"
    }, {
        "id": 10,
        "name": "Robb",
        "surname": "Nequest"
    }, {
        "id": 11,
        "name": "Pat",
        "surname": "Qusklay"
    }, {
        "id": 12,
        "name": "Elias",
        "surname": "Aulds"
    }, {
        "id": 13,
        "name": "Georgie",
        "surname": "Furney"
    }, {
        "id": 14,
        "name": "Lizbeth",
        "surname": "Bramer"
    }, {
        "id": 15,
        "name": "Teodoor",
        "surname": "Shirland"
    }, {
        "id": 16,
        "name": "Hazel",
        "surname": "Bulch"
    }, {
        "id": 17,
        "name": "Marmaduke",
        "surname": "Jillitt"
    }, {
        "id": 18,
        "name": "Eloise",
        "surname": "Bauldrey"
    }, {
        "id": 19,
        "name": "Colby",
        "surname": "Beacon"
    }, {
        "id": 20,
        "name": "Dolley",
        "surname": "Renvoys"
    }, {
        "id": 21,
        "name": "Barbey",
        "surname": "Filshin"
    }, {
        "id": 22,
        "name": "Avril",
        "surname": "Duffil"
    }, {
        "id": 23,
        "name": "Christie",
        "surname": "Wyllie"
    }, {
        "id": 24,
        "name": "Vasily",
        "surname": "MacFarland"
    }, {
        "id": 25,
        "name": "Noland",
        "surname": "Whitebread"
    }, {
        "id": 26,
        "name": "Mei",
        "surname": "Waplinton"
    }, {
        "id": 27,
        "name": "Salaidh",
        "surname": "Dickson"
    }, {
        "id": 28,
        "name": "Karel",
        "surname": "Wadeling"
    }, {
        "id": 29,
        "name": "Herschel",
        "surname": "Labeuil"
    }, {
        "id": 30,
        "name": "Nickie",
        "surname": "Scard"
    }, {
        "id": 31,
        "name": "Ryley",
        "surname": "Figg"
    }, {
        "id": 32,
        "name": "Marty",
        "surname": "Ballintyne"
    }, {
        "id": 33,
        "name": "Morton",
        "surname": "Danick"
    }, {
        "id": 34,
        "name": "Issie",
        "surname": "Waddicor"
    }, {
        "id": 35,
        "name": "Ivor",
        "surname": "Dunkinson"
    }, {
        "id": 36,
        "name": "Dyanne",
        "surname": "Brabant"
    }, {
        "id": 37,
        "name": "Zebulen",
        "surname": "Pine"
    }, {
        "id": 38,
        "name": "Mallorie",
        "surname": "Northwood"
    }, {
        "id": 39,
        "name": "Annabelle",
        "surname": "Whissell"
    }, {
        "id": 40,
        "name": "Chrissy",
        "surname": "Dillinton"
    }, {
        "id": 41,
        "name": "Drusi",
        "surname": "Lightwing"
    }, {
        "id": 42,
        "name": "Riley",
        "surname": "Hedlestone"
    }, {
        "id": 43,
        "name": "Trula",
        "surname": "Alenov"
    }, {
        "id": 44,
        "name": "Lissie",
        "surname": "Faers"
    }, {
        "id": 45,
        "name": "Corenda",
        "surname": "Senyard"
    }, {
        "id": 46,
        "name": "Sinclair",
        "surname": "Kuzemka"
    }, {
        "id": 47,
        "name": "Arlyne",
        "surname": "Apfler"
    }, {
        "id": 48,
        "name": "Sid",
        "surname": "Gawthrope"
    }, {
        "id": 49,
        "name": "Lorene",
        "surname": "McDermott-Row"
    }, {
        "id": 50,
        "name": "Kurtis",
        "surname": "McNiff"
    }, {
        "id": 51,
        "name": "Wain",
        "surname": "Chastey"
    }, {
        "id": 52,
        "name": "Etheline",
        "surname": "Hawse"
    }, {
        "id": 53,
        "name": "Kellsie",
        "surname": "Leathart"
    }, {
        "id": 54,
        "name": "Brunhilda",
        "surname": "Surman-Wells"
    }, {
        "id": 55,
        "name": "Tad",
        "surname": "Klaves"
    }, {
        "id": 56,
        "name": "Idaline",
        "surname": "Fenney"
    }, {
        "id": 57,
        "name": "Kilian",
        "surname": "Dilley"
    }, {
        "id": 58,
        "name": "Juieta",
        "surname": "Huitt"
    }, {
        "id": 59,
        "name": "Yanaton",
        "surname": "Surgen"
    }, {
        "id": 60,
        "name": "Tamara",
        "surname": "Broadey"
    }, {
        "id": 61,
        "name": "Paton",
        "surname": "Futcher"
    }, {
        "id": 62,
        "name": "Simone",
        "surname": "Semper"
    }, {
        "id": 63,
        "name": "Augy",
        "surname": "Kaaskooper"
    }, {
        "id": 64,
        "name": "Jodie",
        "surname": "Surgison"
    }, {
        "id": 65,
        "name": "Coletta",
        "surname": "Pancast"
    }, {
        "id": 66,
        "name": "Sibyl",
        "surname": "McMearty"
    }, {
        "id": 67,
        "name": "Inge",
        "surname": "Dillistone"
    }, {
        "id": 68,
        "name": "Bancroft",
        "surname": "Ilyinski"
    }, {
        "id": 69,
        "name": "Alfie",
        "surname": "Walentynowicz"
    }, {
        "id": 70,
        "name": "Stacy",
        "surname": "Rayner"
    }, {
        "id": 71,
        "name": "Evered",
        "surname": "Urwin"
    }, {
        "id": 72,
        "name": "Michail",
        "surname": "Kitchiner"
    }, {
        "id": 73,
        "name": "Kirsten",
        "surname": "Gaffon"
    }, {
        "id": 74,
        "name": "Sibby",
        "surname": "Culp"
    }, {
        "id": 75,
        "name": "Georgine",
        "surname": "Pirouet"
    }, {
        "id": 76,
        "name": "Patrizius",
        "surname": "Burchard"
    }, {
        "id": 77,
        "name": "Pancho",
        "surname": "Duxbarry"
    }, {
        "id": 78,
        "name": "Debora",
        "surname": "Grandin"
    }, {
        "id": 79,
        "name": "Sigvard",
        "surname": "Kaes"
    }, {
        "id": 80,
        "name": "Gabriello",
        "surname": "Trevear"
    }, {
        "id": 81,
        "name": "Isak",
        "surname": "Eades"
    }, {
        "id": 82,
        "name": "Jessey",
        "surname": "Bartoloma"
    }, {
        "id": 83,
        "name": "Miller",
        "surname": "Hargrave"
    }, {
        "id": 84,
        "name": "Beverly",
        "surname": "Maffin"
    }, {
        "id": 85,
        "name": "Wendell",
        "surname": "Allot"
    }, {
        "id": 86,
        "name": "Durward",
        "surname": "Garlette"
    }, {
        "id": 87,
        "name": "Yettie",
        "surname": "Troughton"
    }, {
        "id": 88,
        "name": "Lethia",
        "surname": "Clayton"
    }, {
        "id": 89,
        "name": "Linnell",
        "surname": "Doonican"
    }, {
        "id": 90,
        "name": "Fredericka",
        "surname": "Goodere"
    }, {
        "id": 91,
        "name": "Avrom",
        "surname": "Jaggi"
    }, {
        "id": 92,
        "name": "Gipsy",
        "surname": "Beurich"
    }, {
        "id": 93,
        "name": "Derward",
        "surname": "Ginity"
    }, {
        "id": 94,
        "name": "Mayne",
        "surname": "Agney"
    }, {
        "id": 95,
        "name": "Guendolen",
        "surname": "Airton"
    }, {
        "id": 96,
        "name": "Chadwick",
        "surname": "Darwent"
    }, {
        "id": 97,
        "name": "Janos",
        "surname": "Roistone"
    }, {
        "id": 98,
        "name": "Katherina",
        "surname": "Benthall"
    }, {
        "id": 99,
        "name": "Rutger",
        "surname": "Russ"
    }, {
        "id": 100,
        "name": "Waldemar",
        "surname": "Bilbey"
    }]
export { navigationLinks, teamMember, googleMapsApi, messenger, childList };